### ISSUE TITLE
Move Id field into fieldList set at initialisation

### ISSUE THREAD

**Issue by florianhoehn** [jpmonette/q#1]
This way you can clean up the toSOQL() method a little bit.

**Comment by jpmonette** [comment]
@florianhoehn Only really low priority challenge here is that if a user only wants select `Name`, I want to remove the `Id` from the query to make the query shorter - the `Id` field would be queried anyway.

How would you rewrite this outside of adding in the constructor the `Id` to the Set?

**Comment by florianhoehn** [comment]
Hmmm..

I think even if I only want to query 'Name' I would still want the query created to be a representation of what actually happens which is querying 'Name' and 'Id'.
